### ISSUE TITLE
SimpleDALPlugin load failed on other mac laptop (Mac10.14), even rebuild on mac 10.14 still load failed. 

### ISSUE THREAD

**Issue by jerrychen44** [seanchas116/SimpleDALPlugin#11]
I rebuild this SimpleDALPlugin under os 10.15 and Xcode 12.0 is ok that can be found by QuickTime as an input camera.

What I really want is I can use this plugin under mac 10.14 also.
What I did ...
(1):
I want to share this plugin file to another mac laptop with os version 10.14, but after moving this file to /Library/CoreMediaIO/Plug-Ins/DAL/, it is not listed as a Quicktime input camera. (Log as below)

(2:)
I rebuild this project on that 10.14 laptop with Xcode 10.1 and still get the same load failed result.
(I change a few swift code and Xcode target from 10.15 to 10.14 to get build pass only.)

Seems like the error keeps showing:  **"dependent dylib '@rpath/libswiftCore.dylib' not found for..."**

Any suggestion will be a big help :)
Thanks.

Log from console:
default	10:56:26.571525 -0500	QuickTime Player	Error loading /Library/CoreMediaIO/Plug-Ins/DAL/SimpleDALPlugin.plugin/Contents/MacOS/SimpleDALPlugin:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/SimpleDALPlugin.plugin/Contents/MacOS/SimpleDALPlugin, 0x0106): dependent dylib '@rpath/libswiftCore.dylib' not found for '/Library/CoreMediaIO/Plug-Ins/DAL/SimpleDALPlugin.plugin/Contents/MacOS/SimpleDALPlugin'

default	10:56:26.571578 -0500	QuickTime Player	Cannot find function pointer simpleDALPluginMain for factory <CFUUID 0x6000014073a0> 25EBE7ED-3E65-4ACF-8DBD-3ABABBF9C161 in CFBundle/CFPlugIn 0x7fb478d29460 </Library/CoreMediaIO/Plug-Ins/DAL/SimpleDALPlugin.plugin> (bundle, not loaded)

**Comment by jerrychen44** [comment]
Updated for who hit this issue.

I solved it by setting "Always Embed Swift Standard Libraries = YES" in the Xcode project setting -> build option.
Solved.
